version: "3"

services:
  frontend:
    build:
      context: ./frontend
    # image: soe153/projectmanagement-frontend:latest
    environment:
      NODE_ENV: development
    depends_on:
      - backend
      - mysql
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
    ports:
      - "0.0.0.0:3000:3030"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    # image: soe153/projectmanagement-backend:latest
    environment:
      APP_ENV: local

    # depends_on:
    #   - mysql
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/app
      - /app/vendor

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sithu
      MYSQL_DATABASE: project
      MYSQL_USER: sithu
      MYSQL_PASSWORD: sithu
    ports:
      - "0.0.0.0:3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: sithu # Update this to match your MySQL user
      PMA_PASSWORD: sithu # Update this to match your MySQL password
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    command: ["apache2-foreground"]

  socket:
    image: node:latest
    container_name: socket
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: ["node", "socket.js"]
